micronaut:
  application:
    name: pubsubEmulatorDemo

gcp:
  project-id: test-project

pubsub:
  emulator:
    host: ${PUBSUB_EMULATOR_HOST:default}
  topic-name: topic-test
  subscription-names:
    - subscription-one

